#include <stdio.h>

/*PROBLEM: Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.*/

int main()
{	
	long num1 = 1;
	long num2 = 2;
	long sum = 0;
	long result=0;
	
	while(result<4000000)
	{    
			
		result = num1 + num2; 
		num1 = num2;
		num2 = result; 
		
		if ((result % 2) == 0)
		{
        	sum = sum + result;
    	}
	}

	printf("%d\n",sum+2);
	
return 0;
}
